float64[] CenterLaneX    # Yellow Marking  Direction --> Front
float64[] CenterLaneY    # Yellow Marking  Direction --> Left
float64[] CenterLaneXRaw # Raw detection result of Yellow Marking  Direction --> Front
float64[] CenterLaneYRaw # Raw detection result of Yellow Marking  Direction --> Left
float64[] CenterLineX    # 2 meter from centerlane  Direction --> Front
float64[] CenterLineY    # 2 meter from centerlane  Direction --> Left
float64[] RightCurbX     # Right Curb  Direction --> Front
float64[] RightCurbY     # Right Curb  Direction --> Left
float64 PolyFitC2        # C2 of the  f(y)=C2x^2+C1x+C0
float64 PolyFitC1        # C1 of the  f(y)=C2x^2+C1x+C0
float64 PolyFitC0        # C0 of the  f(y)=C2x^2+C1x+C0
float64 LateralDis       # C0 of the  f(y)=C2x^2+C1x+C0
float64 Confidence
